name: run on dbt-arc-functions updates

#on:
#  repository_dispatch:
#    repo:
#      name: bsd/dbt-arc-functions

on:
  pull_request_target:
    types: [closed]
    branches: [main]
    # Only trigger for pull requests merging into the main branch of the dbt-arc-functions repository
    paths: 'bsd/dbt-arc-functions/**'

jobs:
  run-python:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run Python script
      run: python main.py
