name: run on dbt-arc-functions updates

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths: 'bsd/dbt-arc-functions/**'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  run-python:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Add this line to enable debug logging
      DEBUG: true
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python script
      run: python main.py

        