name: run on dbt-arc-functions updates

#on:
#  repository_dispatch:
#    repo:
#      name: bsd/dbt-arc-functions

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths: 'bsd/dbt-arc-functions/**'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  run-python:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Add this line to enable debug logging
      DEBUG: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run Python script
      run: python main.py
